# Generated by Django 5.0.4 on 2024-04-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(
                blank=True,
                help_text="Введите цену",
                max_length=100,
                null=True,
                verbose_name="Цена",
            ),
        ),
    ]
