# Generated by Django 5.0.4 on 2024-05-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="views_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
