# Generated by Django 5.0.5 on 2024-05-16 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_blog_views_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.IntegerField(
                        help_text="Ввкдите номер версии", verbose_name="Номер версии"
                    ),
                ),
                (
                    "version_name",
                    models.CharField(
                        help_text="Введите название версии",
                        max_length=100,
                        verbose_name="Название версии",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        help_text="Укажите признак версии",
                        verbose_name="Признак версии",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Продукт",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product",
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
        ),
    ]
