# Generated by Django 5.0.5 on 2024-05-20 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="version",
            options={"verbose_name": "Версия", "verbose_name_plural": "Версии"},
        ),
    ]
