# Generated by Django 4.2.2 on 2024-06-03 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "name"],
                "permissions": [
                    ("can_edit_product", "can cancel product"),
                    ("can_edit_description", "can change description product"),
                    ("can_edit_category", "can change category product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
